name: Tailscale ACL

on:
  push:
    branches: [main]
    paths:
      - "tailscale/**"
  pull_request:
    branches: [main]
    paths:
      - "tailscale/**"

jobs:
  acl:
    name: Tailscale ACL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test ACL
        if: github.event_name == 'pull_request'
        uses: tailscale/gitops-acl-action@v1
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tailnet: ${{ secrets.TS_TAILNET }}
          policy-file: tailscale/policy.hujson
          action: test

      - name: Deploy ACL
        if: github.event_name == 'push'
        uses: tailscale/gitops-acl-action@v1
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tailnet: ${{ secrets.TS_TAILNET }}
          policy-file: tailscale/policy.hujson
          action: apply
